 <!DOCTYPE html>
 <html>

     <head>
         <title>football database</title>
         <?php require("include/meta.phtml"); ?>
     </head>

     <body>

         <div class="row" id="header">
             <div class="col" id="logo"></div>
             <div class="col" id="webTile"> <a id="linkTile" href="index.php">Foot Ball Database</a> </div>
             <div class="col" id="clubLogo">
                 <?php
                    $LoginStatus = "";
                    if(!isset($_SESSION["user"]))
                    {
                        // header("Location: index.php");
                        echo "You are not logged in!";
                        echo "<a href=\"index.php?action=toLoginPage\">Login</a>";
                    }else{
                        $LoginStatus = $_SESSION["user"];
                        echo `Welcome Back $LoginStatus`;
                    } ?>
             </div>
         </div>
         <div class="container">

             <div class="row">
                 <div class="row">
                     <!-- ------------------------------------ -->
                     <!-- ------------------------------------ -->
                     <!-- BEGIN: Nội dung chính của trang web  -->
                     <div class="col-md-8">
                         <?php require($VIEW); ?>
                     </div>
                     <!-- END: Nội dung chính của trang web  -->
                     <!-- ------------------------------------ -->
                     <!-- ------------------------------------ -->
                     <div class="col-md-4">
                         <?php require("include/secondary.phtml"); ?>
                     </div>
                 </div>
             </div>

         </div>
         <div class="row" id="footer">
             <div class="col">
                 <h3>Social</h3>
                 <ul class="noBulletList">
                     <li>
                         <a href="https://www.youtube.com/channel/UCqjNzF4ZBohMUWUtLBfjNzg" class="features"> <i
                                 class="bi bi-youtube"></i> My YT Account </a>
                     </li>
                     <li>
                         <a href="https://www.facebook.com/profile.php?id=100008349376564" class="features"><i
                                 class="bi bi-facebook"></i> My facebook Account</a>
                     </li>
                     <li>
                         <a href="https://github.com/TanNguyen120" class="features"><i class="bi bi-github"></i> My
                             github Account</a>
                     </li>
                     <li>
                         <h3> <i class="bi bi-telephone-inbound"></i> Phone: 097 XXX XXXX</h3>
                     </li>
                     <li>
                         <h3> <i class="bi bi-envelope"></i> Second Email: tannguyen1220@gmail.com </h3>
                     </li>
                 </ul>
             </div>
             <div class="col">
                 <h3>About</h3>
                 <div class="row">
                     <div class="col">
                         <ul class="noBulletList">
                             <li>
                                 <a href="index.php" class="features">Back To Home</a>
                             </li>
                             <li>
                                 <a href="index.php?action=list_player&page=1" class="features">1) List Of Players</a>
                             </li>
                             <li>
                                 <a href="index.php?action=list_club&page=1" class="features">2) List Of Clubs</a>
                             </li>
                             <li>
                                 <a href="index.php?action=findPlayerName" class="features">3) Find Players</a>
                             </li>
                             <li>
                                 <a href="index.php?action=findPlayerName" class="features">4) Find Players With
                                     Filter</a>
                             </li>
                             <li>
                                 <a href="index.php?action=addPlayerPage" class="features">5) Add a Player</a>
                             </li>
                             <li>
                                 <a href="index.php?action=addClubPage" class="features">6) Add a Club</a>
                             </li>
                         </ul>
                     </div>
                     <div class="col">
                         <ul class="noBulletList">

                             <li>
                                 <a href="index.php?action=editClubPage&page=1" class="features">7) Edit Club
                                     Information</a>
                             </li>
                             <li>
                                 <a href="index.php?action=list_player&page=1" class="features">8) Update Player
                                     Information</a>
                             </li>
                             <li>
                                 <a href="index.php?action=list_player&page=1" class="features">9) Delete Players</a>
                             </li>
                             <li>
                                 <a href="index.php?action=toLoginPage" class="features">10) LogIn</a>
                             </li>
                             <li>
                                 <a href=" https://tannguyen1220-pf.netlify.app/index.html" class="features">11) To My
                                     Portfolio</a>
                             </li>
                         </ul>
                     </div>
                 </div>


             </div>
             <div class="col">
                 <h3>Contact</h3>
                 <p>
                     Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex dolores soluta illum corporis,
                     dicta perferendis id eos voluptatibus? Assumenda eveniet rerum sint dolorem. Nam culpa beatae
                     placeat enim, dolorem aliquam.
                 </p>
             </div>
         </div>
     </body>

 </html>