<!DOCTYPE html>
<html>

    <head>
        <title>football database</title>
        <?php require("include/meta.phtml"); ?>
    </head>

    <body>
        <div class="row" id="header">
            <div class="col" id="logo"></div>
            <div class="col" id="webTile"> <a id="linkTile" href="index.php">FOOT BALL DATABASE</a> </div>
            <div class="col" id="logo2"></div>
        </div>
        <div class="container">

            <div class="row">
                <div class="row">
                    <!-- ------------------------------------ -->
                    <!-- ------------------------------------ -->
                    <!-- BEGIN: Nội dung chính của trang web  -->
                    <div class="col-md-8">
                        <?php require($VIEW); ?>
                    </div>
                    <!-- END: Nội dung chính của trang web  -->
                    <!-- ------------------------------------ -->
                    <!-- ------------------------------------ -->
                    <div class="col-md-4">
                        <?php require("include/secondary.phtml"); ?>
                    </div>
                </div>
            </div>

        </div>
        <div class="row" id="footer">
            <div class="col">
                <h3>Social</h3>
                <ul class="noBulletList">
                    <li>
                        <a href="https://www.youtube.com/channel/UCqjNzF4ZBohMUWUtLBfjNzg" class="features"> <i
                                class="bi bi-youtube"></i> My YT Account </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/profile.php?id=100008349376564" class="features"><i
                                class="bi bi-facebook"></i> My facebook Account</a>
                    </li>
                    <li>
                        <a href="https://github.com/TanNguyen120" class="features"><i class="bi bi-github"></i> My
                            github Account</a>
                </ul>
            </div>
            <div class="col">
                <h3>About</h3>
                <ul class="noBulletList">
                    <li>
                        <a href="index.php" class="features">Back To Home</a>
                    </li>
                    <li>
                        <a href="index.php?action=list" class="features">List Of Player</a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <h3>Contact</h3>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex dolores soluta illum corporis,
                    dicta perferendis id eos voluptatibus? Assumenda eveniet rerum sint dolorem. Nam culpa beatae
                    placeat enim, dolorem aliquam.
                </p>
            </div>
        </div>
    </body>

</html>