<?php
require_once("./controller/Home.php");
require_once("./controller/Player.php");
require_once("./model/SinhVien.php");
require_once("./model/Player.php");
require_once("./model/Club.php");
require_once("./controller/Club.php");
require_once("./model/Stadium.php");
require_once("./model/Coach.php");
require_once("config/dbconnect.php");