<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<!-- bootstrap cnd -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- bootstrap icon -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<!-- font -->
<link href="http://fonts.cdnfonts.com/css/radikal" rel="stylesheet">

<!-- web css -->
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/paging.css" rel="stylesheet" type="text/css" />

<!-- Jquery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<!-- web script -->
<script src="javascript/script.js"></script>