<div class="sidebox">
    <h2>Introduce</h2>
    <div class="vmenu">
        <ul>
            <li>
                Author: 1612599 - Nguyễn Việt Tân
            </li>
            <li>
                Email: <br /> <a href="mailto:1612599@student.hcmus.edu.vn">1612599@student.hcmus.edu.vn</a>
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">
    <h2>Feature</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php" class="features">Back To Home</a>
            </li>
            <li>
                <a href="index.php?action=list_player&page=1" class="features">1) List Of Players</a>
            </li>
            <li>
                <a href="index.php?action=list_club&page=1" class="features">2) List Of Clubs</a>
            </li>
            <li>
                <a href="index.php?action=findPlayerName" class="features">3) Find Players</a>
            </li>
            <li>
                <a href="index.php?action=findPlayerName" class="features">4) Find Players With Filter</a>
            </li>
            <li>
                <a href="index.php?action=addPlayerPage" class="features">5) Add a Player</a>
            </li>
            <li>
                <a href="index.php?action=addClubPage" class="features">6) Add a Club</a>
            </li>
            <li>
                <a href="index.php?action=editClubPage&page=1" class="features">7) Edit Club Information</a>
            </li>
            <li>
                <a href="index.php?action=list_player&page=1" class="features">8) Update Player Information</a>
            </li>
            <li>
                <a href="index.php?action=list_player&page=1" class="features">9) Delete Players</a>
            </li>
            <li>
                <a href="index.php?action=toLoginPage" class="features">10) LogIn</a>
            </li>
            <li>
                <a href=" https://tannguyen1220-pf.netlify.app/index.html" class="features">11) To My Portfolio</a>
            </li>


        </ul>
    </div>
</div>