<div class="sidebox">
    <h2>Introduce</h2>
    <div class="vmenu">
        <ul>
            <li>
                Author: 1612599 - Nguyễn Việt Tân
            </li>
            <li>
                Email: <br /> <a href="mailto:1612599@student.hcmus.edu.vn">1612599@student.hcmus.edu.vn</a>
            </li>
        </ul>
    </div>

</div>

<div class="sidebox">
    <h2>Feature</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php" class="features">Back To Home</a>
            </li>
            <li>
                <a href="index.php?action=list_player&page=1" class="features">List Of Players</a>
            </li>
            <li>
                <a href="index.php?action=list_club&page=1" class="features">List Of Clubs</a>
            </li>
        </ul>
    </div>
</div>