<h1>list_club Of all club in data base</h1>
<hr />
<div class="row"><a href="index.php?action=editClubPage&page=1">Edit Club Page</a>
</div>
<div class="row"><a href="index.php?action=addClubPage">Add Club Page</a>
</div>
<table class="table results" id="results">
    <thead>
        <tr>
            <th scope="col">ClubID</th>
            <th scope="col">ClubName</th>
            <th scope="col">ShortName</th>
            <th scope="col">Stadium</th>
            <th scope="col">Coach</th>
        </tr>
    </thead>
    <tbody>
        <?php
            $i = 1;
            foreach ($data as $item) 
            {   
                echo "<tr class='clubResult'>";
                echo "<th>".$item->ClubID."</th>";
                echo "<td contenteditable='true'>".$item->ClubName."</td>";
                echo "<td contenteditable='true'>".$item->ShortName."</td>";
                echo "<td>".$item->Stadium."</td>";
                echo "<td>".$item->Coach."</td>";
                echo "</tr>";
                $i++;
            }
        ?>
    </tbody>
</table>
<!-- phần pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php
            $wantPage = $page - 1;
            if($wantPage > 0) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list_club&page=${wantPage}\">Previous</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Previous</a></li>";
            }
        ?>

        <?php
            for ($i = 1; $i <= $pageCount; $i++) {
                if($i == $page) {
                    echo "<li class=\"page-item active\"><a class=\"page-link\" href=\"Index.php?action=list_club&page=${i}\">${i}</a></li>";
                } else {
                    echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list_club&page=${i}\">${i}</a></li>";
                }
            }
        ?>
        <?php
            $wantPage = $page + 1;
            if($wantPage <= $pageCount) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list_club&page=${wantPage}\">Next</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Next</a></li>";
            }
        ?>
    </ul>
</nav>