<h1>Change Club Information</h1>
<hr />

<table class="table results" id="results">
    <thead>
        <tr>
            <th scope="col">ClubID</th>
            <th scope="col">ClubName</th>
            <th scope="col">ShortName</th>
            <th scope="col">Stadium</th>
            <th scope="col">Coach</th>
        </tr>
    </thead>
    <tbody>
        <?php
            // tao table tu ket qua o controller
            $i = 1;
            foreach ($data as $item) 
            {   
                echo "<tr class='clubResultEdit'>";
                echo "<th>".$item->ClubID."</th>";
                echo "<td contenteditable='true'>".$item->ClubName."</td>";
                echo "<td contenteditable='true'>".$item->ShortName."</td>";

                //tao combo box cho viec chon san van dong
                echo "<td> <select class=\"form-select\" t aria-label=\"Nationality\" id=\"stadiumSelectClubEdit\" name=\"StadiumID\">";
                foreach($stadiums as $row){
                    if(strcmp($row->SName, $item->Stadium)==0)
                    {
                         echo '<option selected="selected" value='.$row->StadiumID.'>'.$row->SName."</option>";

                    }else{
                    echo '<option value='.$row->StadiumID.'>'.$row->SName."</option>";
                    };
                };
                echo"</select></td>";

                //tao combo box cho viec edit huan luyen vien
                echo "<td> <select class=\"form-select\" t aria-label=\"Nationality\" id=\"coachSelectClubEdit\" name=\"CoachID\">";
                foreach($coaches as $row){
                    if(strcmp($row->CFullName, $item->Coach)==0)
                    {
                         echo '<option selected="selected" value='.$row->CoachID.'>'.$row->CFullName."</option>";

                    }else{
                    echo '<option value='.$row->CoachID.'>'.$row->CFullName."</option>";
                    };
                };
                echo"</select></td>";
                echo "</tr>";
                $i++;
            }
        ?>
    </tbody>
</table>
<!-- phần pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php
            $wantPage = $page - 1;
            if($wantPage > 0) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=editClubPage&page=${wantPage}\">Previous</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Previous</a></li>";
            }
        ?>

        <?php
            for ($i = 1; $i <= $pageCount; $i++) {
                if($i == $page) {
                    echo "<li class=\"page-item active\"><a class=\"page-link\" href=\"Index.php?action=editClubPage&page=${i}\">${i}</a></li>";
                } else {
                    echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=editClubPage&page=${i}\">${i}</a></li>";
                }
            }
        ?>
        <?php
            $wantPage = $page + 1;
            if($wantPage <= $pageCount) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=editClubPage&page=${wantPage}\">Next</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Next</a></li>";
            }
        ?>
    </ul>
</nav>