<h1>List Of all player in database</h1>
<hr />

<form action="Index.php" method="get">
    <input type="text" name="keyword" />
    <input type="submit" value="search" />
    <input type="hidden" name="action" value="search" />
</form>

<table class="table results" id="results">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">FullName</th>
            <th scope="col">Club</th>
            <th scope="col">Nationality</th>
            <th scope="col">Position</th>
            <th scope="col">Number</th>
        </tr>
    </thead>
    <tbody>
        <?php
            $i = 1;
            foreach ($data as $item) 
            {
                echo "<tr>";
                echo "<th scope=\"row\">${i}</th>";
                echo "<td>".$item->FullName."</td>";
                echo "<td>".$item->ClubID."</td>";
                echo "<td>".$item->Nationality."</td>";
                echo "<td>".$item->Position."</td>";
                echo "<td>".$item->Number."</td>";
                echo "</tr>";
                $i++;
            }
        ?>
    </tbody>
</table>
<!-- phần pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php
            $wantPage = $page - 1;
            if($wantPage >= 0) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list&page=${wantPage}\">Previous</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Previous</a></li>";
            }
        ?>

        <?php
            for ($i = 1; $i <= $pageCount; $i++) {
                if($i == $page) {
                    echo "<li class=\"page-item active\"><a class=\"page-link\" href=\"Index.php?action=list&page=${i}\">${i}</a></li>";
                } else {
                    echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list&page=${i}\">${i}</a></li>";
                }
            }
        ?>
        <?php
            $wantPage = $page + 1;
            if($wantPage <= $pageCount) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=list&page=${wantPage}\">Next</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Next</a></li>";
            }
        ?>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>