<h1><?php echo $webTile ?></h1>
<hr />

<div class="row">
    <div class="col-md-6">
        <div class="input-group rounded">
            <input type="search" class="form-control rounded" id="searchNameVal" placeholder="Search Player with name"
                aria-label="Search" aria-describedby="search-addon" />
            <span class="input-group-text border-0" id="search-addon-searchPlayerName">
                <i class="bi bi-search" id="playerNameSearch"></i>
            </span>
        </div>
    </div>
    <div class="col"></div>
</div>

<table class="table results" id="results">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">FullName</th>
            <th scope="col">Club</th>
            <th scope="col">Nationality</th>
            <th scope="col">Position</th>
            <th scope="col">Number</th>
        </tr>
    </thead>
    <tbody>
        <?php
            $i = 1;
            foreach ($data as $item) 
            {
                echo "<tr class=\"ListPlayerTableRow\">";
                echo "<th scope=\"row\">${i}</th>";
                echo "<td>".$item->FullName."</td>";
                echo "<td>".$item->ClubID."</td>";
                echo "<td>".$item->Nationality."</td>";
                echo "<td>".$item->Position."</td>";
                echo "<td>".$item->Number."</td>";
                echo "</tr>";
                $i++;
            }
        ?>
    </tbody>
</table>
<!-- phần pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php
            $wantPage = $page - 1;
            if($wantPage >= 0) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=searchPlayerName&page=${wantPage}&playerName=${playerName}\">Previous</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Previous</a></li>";
            }
        ?>

        <?php
            for ($i = 1; $i <= $pageCount; $i++) {
                if($i == $page) {
                    echo "<li class=\"page-item active\"><a class=\"page-link\" href=\"Index.php?action=searchPlayerName&page=${i}&playerName=${playerName}\">${i}</a></li>";
                } else {
                    echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=searchPlayerName&page=${i}&playerName=${playerName}\">${i}</a></li>";
                }
            }
        ?>
        <?php
            $wantPage = $page + 1;
            if($wantPage <= $pageCount) {
                echo "<li class=\"page-item\"><a class=\"page-link\" href=\"Index.php?action=searchPlayerName&page=${wantPage}&playerName=${playerName}\">Next</a></li>";
            }else {
                echo "<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Next</a></li>";
            }
        ?>
    </ul>
</nav>